# Generated by Django 6.0.7 on 2026-08-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_like_post_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
